# Path to BCL folder
bcl: ~
# Path to SampleSheet
sample_sheet: ~
# Output directory
out_dir: "."
# Analysis to use in case of NOT re-demux (0 means latest)
analysis_n: 0
# If folder exists, resume
resume: no
# Index list (path has to be absolute or relative to workflow basedir)
idx_list: "resources/IndexInformation_20260819JBT_RC.tsv"
