import os
import re
from pathlib import Path
import pandas as pd
from collections import defaultdict
from samshee.samplesheetv2 import read_samplesheetv2

header = """
# Name: SnakeDemux
# Description: Snakemake workflow to demux Illumina runs using bcl-convert.
# Version: 0.1.0 (2026-07-28)
# Author: Filipe G. Vieira
# Mail: fgvieira@sund.ku.dk
"""


####################
### Sample Sheet ###
####################
sample_sheet = Path(config["sample_sheet"])
ss = read_samplesheetv2(sample_sheet)
# Reads
ss_reads = range(
    1,
    len(
        [
            read
            for read in ss.reads
            if read.startswith("Read") and read.endswith("Cycles")
        ]
    )
    + 1,
)
# Pools
ss_pools = defaultdict(list)
[
    ss_pools[val].append(tag.removeprefix("PoolLane"))
    for tag, val in ss.header.items()
    if tag.startswith("PoolLane")
]
# Samples
ss_samples = pd.DataFrame.from_dict(ss.applications["BCLConvert"]["data"])
# Assign lanes
if "Lane" not in ss_samples.columns:
    ss_lanes = [
        int(tag.removeprefix("PoolLane"))
        for tag, val in ss.header.items()
        if tag.startswith("PoolLane")
    ]
    ss_samples = ss_samples.assign(Lane=[ss_lanes] * len(ss_samples)).explode("Lane")
ss_lanes = ss_samples["Lane"].unique().tolist()
# Add Undetermined
ss_samples = pd.concat(
    [
        pd.DataFrame(
            {
                "Sample_ID": "Undetermined",
                "Sample_Project": "Undetermined",
                "Lane": [ss_lanes],
            },
            index=[0],
        ).explode("Lane"),
        ss_samples,
    ],
    ignore_index=True,
)
# Assign sample numbers
ss_samples["sample_n"] = pd.factorize(ss_samples["Sample_ID"])[0]
assert (
    ss_samples.drop(columns="Lane")
    .groupby(["Sample_ID", "index", "index2"])
    .nunique()["sample_n"]
    .eq(1)
    .all()
), "Sample_ID have different Sample_N. Check your main Samplesheet."
# Assign R1/R2
ss_samples = (
    ss_samples.assign(read=[ss_reads] * len(ss_samples)).explode("read").astype("str")
)


###########
### BCL ###
###########
in_dir = Path(config["bcl"])
in_analyses = in_dir / "Analysis"
if in_analyses.exists():
    # Choose analysis, by default is the last
    in_analysis = sorted(in_analyses.glob("[0-9]/Data"))[
        config.get("analysis_n", 0) - 1
    ]

    assert in_dir / "CopyComplete.txt", "File CopyComplete.txt is not present!"
    assert (
        in_analysis / "Secondary_Analysis_Complete.txt"
    ), "File Secondary_Analysis_Complete.txt is not present!"

    print(
        f"""Found analysis data in '{in_analysis}'. Do you want to demultiplex this data again? [y/n/q]: """,
        end="",
	file=sys.stderr,
    )
    demux = config.get("demux")
    if not demux:
        from builtins import input as user_input
        demux = user_input()

    match demux:
        case "y" | "Y" | "yes" | "Yes" | "YES":
            print("Re-demultiplexing data...", file=sys.stderr)
            demux = True
        case "n" | "N" | "no" | "No" | "NO":
            print("Using existing data...", file=sys.stderr)
            demux = False
        case "q" | "Q" | "quit" | "Quit" | "QUIT":
            print("Quitting...", file=sys.stderr)
            exit(0)
        case _:
            print("Unknown command!", file=sys.stderr)
            exit(1)
else:
    print(
        f"""Demultiplexing locally (could not find '{in_dir / "Analysis"}' folder).""",
	file=sys.stderr,
    )
    demux = True
assert sum(ss_samples["Sample_ID"].isna()) == 0, "Some entries do not have a Sample_ID."


# Projects
ss_proj = (
    ss_samples.query('Sample_Project != "Undetermined"')["Sample_Project"]
    .unique()
    .tolist()
)


### Check if run_id a sample_sheet match (date and side)
ss_id = re.match(
    r"(?P<date>\d{6})_samplesheet_(?P<flowcell_type>\w+)(?P<side>[AB])",
    sample_sheet.name,
).groupdict()
run_id = re.search(
    r"(?P<date>\d{6})_(?P<instrument>[A-Z]{1,2}\d{5})_(?P<run_n>\d+)_(?P<side>[AB])(?P<flowcell_id>\w{9})",
    in_dir.name,
).groupdict()
assert (
    ss_id["date"] == run_id["date"]
    and ss_id["side"] == run_id["side"]
    and ss.header.get("FlowcellID") == run_id["flowcell_id"]
), "run and samplesheet do not match"


### Run ID - add 20 year prefix, if not present
run_id = in_dir.name
if not run_id.startswith("20"):
    run_id = f"20{run_id}"


##############
### Output ###
##############
out_dir = Path(config["out_dir"])
if out_dir.absolute() == "/maps/datasets/caeg_fastq":
    out_dir = out_dir / run_id[0:4]
    caeg_data = True
else:
    caeg_data = False
# Check if folder exists
assert not (out_dir / run_id).exists() or config.get(
    "resume", False
), f"Output folder {out_dir / run_id} already exists! Please rename folder and re-try."


# Import extra rules
include: "rules/bcl_convert.smk" if demux else "rules/copy.smk"
include: "rules/qc.smk"
include: "rules/smdb.smk"


# Copy log
onsuccess:
    shell("cp {log} {out_dir}/{run_id}/.")


wildcard_constraints:
    run_id=run_id,
    Sample_Project="|".join(ss_proj + ["Undetermined"]),
    pool="|".join(ss_pools.keys()),
    sample_n=r"\d+",
    Lane="|".join(map(str, ss_lanes)),
    read="|".join(map(str, ss_reads)),


# Rules
rule qc:
    input:
        rules.bcl_convert.log if demux else [],
        rules.qc_undetermined_adapters.output,
        expand(
            rules.qc_fastq_size.output,
            Sample_Project=ss_proj + ["Undetermined"],
            allow_missing=True,
        ),
        expand(
            rules.qc_fastq_md5sum_cat.log, Sample_Project=ss_proj, allow_missing=True
        ),
        expand(
            rules.qc_cross_contamination.log, pool=ss_pools.keys(), allow_missing=True
        ),
        rules.smdb_upload.log if os.environ.get("DB_PASSWORD") and caeg_data else [],
    output:
        touch(out_dir / "{run_id}/{run_id}.log"),
    shell:
        "head -n 1000000 {input} > {output}"


rule demux:
    input:
        ### Logs
        #expand(
        #    out_dir / "{run_id}/Logs/{log}.log",
        #    log=["Info", "Warnings", "Errors"],
        #),
        ### Reports
        expand(
            out_dir / "{run_id}/Reports/{report}",
            run_id=run_id,
            report=[
                "RunCompletionStatus.xml",
                "RunInfo.xml",
                "RunParameters.xml",
                "SampleSheet.csv",
                "Demultiplex_Stats.csv",
                "Demultiplex_Tile_Stats.csv",
                "Index_Hopping_Counts.csv",
                "IndexMetricsOut.bin",
                "Top_Unknown_Barcodes.csv",
                "Adapter_Cycle_Metrics.csv",
                "Adapter_Metrics.csv",
                "Quality_Metrics.csv",
                "Quality_Tile_Metrics.csv",
            ],
        ),
        ### FASTQC
        [
            expand(rules.reports_fastqc.output, **sample, allow_missing=True)
            for sample in ss_samples.assign(
                type=[["fastqc_metrics", "trimmer_metrics"]] * len(ss_samples)
            )[ss_samples["Sample_Project"].ne("Undetermined")]
            .explode("type")
            .to_dict("records")
        ]
        if not demux
        else [],
        ### FASTQ
        [
            expand(rules.fastq_sample.output, **sample, allow_missing=True)
            for sample in ss_samples.to_dict("records")
        ],
        # QC
        rules.qc.output,
    output:
        touch(out_dir / "{run_id}/seqcenter.done"),
    message:
        "Demultiplexing done!"


rule all:
    default_target: True
    input:
        expand(rules.demux.output, run_id=run_id),
